import Header from '@/components/header/Header';
import './globals.css';
import { Poppins } from 'next/font/google';
import Footer from '@/components/footer/Footer';

const font = Poppins({
  subsets: ['latin'],
  weight: ['300', '600', '700', '900'],
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="flex flex-col min-h-[100vh] bg-white">
          <Header />
          <main className="flex-grow md:mt-40">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
